// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDd9ty8Ubel98gtj7E_ZmdbnLqouLjT4eM',
    appId: '1:778438585678:web:a1747c6e8ca08495b8021f',
    messagingSenderId: '778438585678',
    projectId: 'simpan-ku',
    authDomain: 'simpan-ku.firebaseapp.com',
    storageBucket: 'simpan-ku.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQGkQkMek0yxBECeThuoiZcsQaXCEsXqQ',
    appId: '1:778438585678:android:b01b52b7f643381eb8021f',
    messagingSenderId: '778438585678',
    projectId: 'simpan-ku',
    storageBucket: 'simpan-ku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBc-W0Je6HV-M1YndqOZChY3As-Te5upNA',
    appId: '1:778438585678:ios:436231f0592ae57eb8021f',
    messagingSenderId: '778438585678',
    projectId: 'simpan-ku',
    storageBucket: 'simpan-ku.firebasestorage.app',
    iosBundleId: 'com.ola.patternGetxCli',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBc-W0Je6HV-M1YndqOZChY3As-Te5upNA',
    appId: '1:778438585678:ios:436231f0592ae57eb8021f',
    messagingSenderId: '778438585678',
    projectId: 'simpan-ku',
    storageBucket: 'simpan-ku.firebasestorage.app',
    iosBundleId: 'com.ola.patternGetxCli',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDd9ty8Ubel98gtj7E_ZmdbnLqouLjT4eM',
    appId: '1:778438585678:web:ad0a4350341c673eb8021f',
    messagingSenderId: '778438585678',
    projectId: 'simpan-ku',
    authDomain: 'simpan-ku.firebaseapp.com',
    storageBucket: 'simpan-ku.firebasestorage.app',
  );
}
